### ISSUE TITLE
ros2 use

### ISSUE THREAD

**Issue by tbcky** [kpierczy/scan-tools#1]
After I use ros2 compilatio：
- stderr: laser_scan_matcher                         
CMake Error at CMakeLists.txt:66 (find_package):
  By not providing "Findcmake_common.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "cmake_common", but CMake did not find one.

  Could not find a package configuration file provided by "cmake_common" with
  any of the following names:

    cmake_commonConfig.cmake
    cmake_common-config.cmake

  Add the installation prefix of "cmake_common" to CMAKE_PREFIX_PATH or set
  "cmake_common_DIR" to a directory containing one of the above files.  If
  "cmake_common" provides a separate development package or SDK, be sure it
  has been installed.

**Comment by kpierczy** [comment]
`cmake_common` package is part of my external project [`ros-common`](https://github.com/kpierczy/ros-common) that is linked to this repository as a git submodule :wink: Before you use

```
source /opt/ros/<your-ros2-distro>/setup.bash
colcon build
```

to build the project you need to simply initialize submodules using

```
git submodule update --init --recursive
```
